name: Mirror Repository

on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the repository xm-webapp.git from xm-online to xme-digital
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "git@github.com:xm-online/xm-webapp.git"
          destination_repo: "git@github.com:xme-digital/xm-webapp.git"
          sync_tags: "true"
          git_ssh_private_key: ${{ secrets.GH_MIRROR_TOKEN }}
