name: Bulk Repository Mirroring

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror Repositories
        run: |
          REPOS=(
            "generator-jhipster-xm"
            "tmf-ms-account"
            "tmf-ms-activation"
            "tmf-ms-communication"
            "tmf-ms-customer"
            "tmf-ms-document"
            "tmf-ms-interaction"
            "tmf-ms-loyalty"
            "tmf-ms-offering"
            "tmf-ms-order"
            "tmf-ms-prepaybalance"
            "tmf-ms-product"
            "tmf-ms-promotion"
            "tmf-ms-qualification"
            "tmf-ms-resource"
            "tmf-ms-resource-pool"
            "xm-commons"
            "xm-gate"
            "xm-lep"
            "xm-ms-balance"
            "xm-ms-config"
            "xm-ms-config-repository"
            "xm-ms-dashboard"
            "xm-ms-entity"
            "xm-ms-otp"
            "xm-ms-scheduler"
            "xm-ms-template"
            "xm-ms-timeline"
            "xm-online"
            "xm-online-idea-plugin"
            "xm-uaa"
            "xm-ms-webapp"
          )
          for REPO in "${REPOS[@]}"; do
            echo "--- Mirroring ${REPO} ---"
            
            git clone --mirror "https://github.com/xm-online/${REPO}.git"
            echo "Cloned ${REPO}"

            cd "${REPO}.git"
            echo "Changed directory to ${REPO}.git"
            
            echo "Setting up push mirror to xme-digital/${REPO}"
            git remote add --mirror=fetch push-mirror "https://x-access-token:${{ secrets.GH_MIRROR_TOKEN }}@github.com/xme-digital/${REPO}.git"
            echo "Configured push-mirror remote"
            
            git config remote.push-mirror.push '+refs/heads/*:refs/heads/*'
            echo "Configured push-mirror for branches"
            
            git config --add remote.push-mirror.push '+refs/tags/*:refs/tags/*'
            echo "Configured push-mirror for tags"
            
            # [remote rejected] refs/pull/6/head -> refs/pull/6/head (deny updating a hidden ref)
            # git config --add remote.push-mirror.push '+refs/pull/*/head:refs/pull/*/head'
            # echo "Configured push-mirror for pull requests"

            git push --mirror push-mirror
            echo "Pushed all refs to push-mirror"
            cd ..
            rm -rf "${REPO}.git"
            echo "--- Done with ${REPO} ---"
          done