name: Bulk Repository Mirroring

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror Repositories via HTTPS
        run: |
          REPOS=(
            "xm-webapp"
            "xm-ms-entity"
            "tmf-ms-communication"
          )
          for REPO in "${REPOS[@]}"; do
            echo "--- Mirroring ${REPO} ---"
            
            git clone --mirror "https://github.com/xm-online/${REPO}.git"
            
            cd "${REPO}.git"
            
            git remote add --mirror=fetch push-mirror "https://x-access-token:${{ secrets.GH_MIRROR_TOKEN }}@github.com/xme-digital/${REPO}.git"
            
            git config --add remote.push-mirror.push 'refs/remotes/*:refs/heads/*'
            git config --add remote.push-mirror.push '+refs/tags/*:refs/tags/*'
            
            git push --mirror
            
            cd ..
            rm -rf "${REPO}.git"
            echo "--- Done with ${REPO} ---"
          done