name: Bulk Repository Mirroring

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror Repositories via HTTPS
        run: |
          REPOS=(
            "xm-webapp"
            "xm-ms-entity"
            "tmf-ms-communication"
          )
          for REPO in "${REPOS[@]}"; do
            echo "Mirroring ${REPO}..."
            
            git clone --mirror "https://github.com/xm-online/${REPO}.git"
            
            cd "${REPO}.git"
            
            git git push --mirror "https://x:$GITHUB_TOKEN@github.com/xme-digital/${REPO}.git"

            cd ..
            rm -rf "${REPO}.git"
            echo "Done with ${REPO}."
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GH_MIRROR_TOKEN }}